/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { StorageAbi, StorageAbiInterface } from "../StorageAbi";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "num",
        type: "uint256",
      },
    ],
    name: "store",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "retrieve",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class StorageAbi__factory {
  static readonly abi = _abi;
  static createInterface(): StorageAbiInterface {
    return new utils.Interface(_abi) as StorageAbiInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): StorageAbi {
    return new Contract(address, _abi, signerOrProvider) as StorageAbi;
  }
}
