/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { Storage2Abi, Storage2AbiInterface } from "../Storage2Abi";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "_from",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_value",
        type: "uint256",
      },
    ],
    name: "Store",
    type: "event",
  },
  {
    inputs: [],
    name: "retrieve",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "num",
        type: "uint256",
      },
    ],
    name: "store",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class Storage2Abi__factory {
  static readonly abi = _abi;
  static createInterface(): Storage2AbiInterface {
    return new utils.Interface(_abi) as Storage2AbiInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Storage2Abi {
    return new Contract(address, _abi, signerOrProvider) as Storage2Abi;
  }
}
