/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { StorageAbi } from "./StorageAbi";

export { StorageAbi__factory } from "./factories/StorageAbi__factory";
