/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { StorageAbi } from "./StorageAbi";
export type { Storage2Abi } from "./Storage2Abi";

export { StorageAbi__factory } from "./factories/StorageAbi__factory";
export { Storage2Abi__factory } from "./factories/Storage2Abi__factory";
